// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<GuiPairingEvent> startGuiServer() =>
    RustLib.instance.api.crateApiStartGuiServer();

Future<void> stopGuiServer() => RustLib.instance.api.crateApiStopGuiServer();

Future<void> respondPairingDecision({required bool accept}) =>
    RustLib.instance.api.crateApiRespondPairingDecision(accept: accept);

Future<List<GuiDeviceInfo>> scanNetworkDevices() =>
    RustLib.instance.api.crateApiScanNetworkDevices();

Future<List<GuiFileIndexing>> getRemoteDeviceFiles(
        {required String targetIp, required String targetName}) =>
    RustLib.instance.api.crateApiGetRemoteDeviceFiles(
        targetIp: targetIp, targetName: targetName);

Future<void> downloadFileFromRemote(
        {required String targetIp,
        required String targetName,
        required BigInt fileId}) =>
    RustLib.instance.api.crateApiDownloadFileFromRemote(
        targetIp: targetIp, targetName: targetName, fileId: fileId);

Future<List<String>> getShareRoots() =>
    RustLib.instance.api.crateApiGetShareRoots();

Future<void> updateShareRoots({required List<String> newRoots}) =>
    RustLib.instance.api.crateApiUpdateShareRoots(newRoots: newRoots);

class GuiDeviceInfo {
  final int index;
  final String name;
  final String ip;

  const GuiDeviceInfo({
    required this.index,
    required this.name,
    required this.ip,
  });

  @override
  int get hashCode => index.hashCode ^ name.hashCode ^ ip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuiDeviceInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          ip == other.ip;
}

class GuiFileIndexing {
  final BigInt id;
  final String name;
  final BigInt size;
  final String path;
  final bool isDir;
  final String? parentDir;

  const GuiFileIndexing({
    required this.id,
    required this.name,
    required this.size,
    required this.path,
    required this.isDir,
    this.parentDir,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      size.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      parentDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuiFileIndexing &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          size == other.size &&
          path == other.path &&
          isDir == other.isDir &&
          parentDir == other.parentDir;
}

class GuiPairingEvent {
  final String deviceName;
  final String fingerprint;

  const GuiPairingEvent({
    required this.deviceName,
    required this.fingerprint,
  });

  @override
  int get hashCode => deviceName.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuiPairingEvent &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          fingerprint == other.fingerprint;
}
